package co.edu.cue.practicas.model.enums;

public enum TipoAccion {
    LOGIN_EXITOSO,
    LOGIN_FALLIDO,
    LOGOUT,
    CREAR,
    EDITAR,
    DESACTIVAR,
    ACTIVAR,
    CAMBIO_ESTADO,
    ACCESO_NO_AUTORIZADO,
    RESET_PASSWORD,
    CAMBIO_PASSWORD,
    CAMBIO_CORREO,
    EXPORTAR,
    CONSULTAR,
    CONFIRMAR,
    SUBIR_DOCUMENTO,
    FIRMAR,
    ASIGNAR,
    CERRAR,
    CALIFICAR
}
