package co.edu.cue.practicas.model.enums;

public enum TipoEventoNotificacion {
    INICIO_PRACTICA,
    EVALUACION_DOCENTE_COMPLETADA,
    EVALUACION_TUTOR_COMPLETADA,
    NOTA_FINAL_REGISTRADA,
    ENCUESTA_TUTOR_ENVIADA,
    ENCUESTA_ESTUDIANTE_ENVIADA,
    ENCUESTA_COMPLETADA,
    CIERRE_FORMAL_EJECUTADO,
    COORDINACION_ACADEMICA_RESULTADO
}
